### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by csm123** [olbrich/ruby-units#104]
On this: Unit.new("1 to 1 1/4 lbs")

I understand that the provided value is not valid for ruby-units, but a more catchable error would be very helpful.

**Comment by kreintjes** [comment]
Other examples that crash: `Unit.new('m^2/1')` and `Unit.new('m^3/1')`.

However, `Unit.new('m/1')` and `Unit.new('m^2')/Unit.new('1')` do work.
