### ISSUE TITLE
Is RubyUnits::Unit#unit_name still used?

### ISSUE THREAD

**Issue by davidstosik** [olbrich/ruby-units#111]
Hello,

Commit 29c9466 deletes all lines that set `@unit_name` in `RubyUnits::Unit`, but `attr_accessor :unit_name` is [still there](https://github.com/olbrich/ruby-units/blob/master/lib/ruby_units/unit.rb#L244).

Was this an omission?

Thanks,
David

**Comment by cromwellryan** [comment]
`@unit_name` is set in lines [315](https://github.com/olbrich/ruby-units/blob/29c9466e348a2c9f54206ff4fab9295f4888795a/lib/ruby_units/unit.rb#L315) and [263](https://github.com/olbrich/ruby-units/blob/29c9466e348a2c9f54206ff4fab9295f4888795a/lib/ruby_units/unit.rb#L263).

**Comment by dstosik** [comment]
Being set does not mean it's ever used, and it does not seem to be. ;)

**Comment by cromwellryan** [comment]
[Fair enough](https://github.com/olbrich/ruby-units/search?utf8=%E2%9C%93&q=unit_name), but I was (in my head) referring to external usages.

**Comment by mathieujobin** [comment]
I was expecting

```ruby
'34 mm'.to_unit.unit_name
```
to return `mm` but it did not, now I just found `#units`, that method will remain, correct?

**Comment by olbrich** [comment]
I have no plans to remove `#units`
