### ISSUE TITLE
Date.rb is not namespaced

### ISSUE THREAD

**Issue by gsusmonzon** [olbrich/ruby-units#112]
Hello,

The file date.rb is using a bare `Unit`. 
In other parts of the library, the proper `RubyUnits::Unit` is used.

Otherwise, it could interact with a previously defined `Unit` class

**Comment by cromwellryan** [comment]
We've patched this in [our fork](https://github.com/sparkbox/ruby-units/tree/fix-prefix-date-unit).  We're working through a test that will assure `RubyUnits::Unit` is namespace accordingly, before submitting the PR.

**Comment by saki7** [comment]
My PR #115 fixes this issue.

**Comment by saki7** [comment]
This issue has been fixed since the PR has been merged. Thanks to all!

**Comment by cromwellryan** [comment]
👍
