### ISSUE TITLE
Dividing Weight into Weight

### ISSUE THREAD

**Issue by richseviora** [olbrich/ruby-units#113]
I've ran into what I initially considered a peculiar result when dividing units of the same kind in that it doesn't eliminate the common denominators and return a scalar result. 

Of course I can convert everything into the same base unit, however I'm wondering if there's an option to deal with this a bit more elegantly. I appreciate that there may be times when you'd need to specify the number of mass units per mass unit. Example:
> 50mg of active ingredients per 1g of unit weight.

```ruby
5.to_unit('g') / 5.to_unit('g') # Returns 1. Expected.
5.to_unit('kg') / 5.to_unit('g') # 1 kg/g. Not expected.
5.to_unit('kg') / 5.to_unit('pounds') # 1 kg/pounds. Not expected.
```

**Comment by olbrich** [comment]
you can call `to_base` on the return value to simplify the result.
