### ISSUE TITLE
Publish next release 1.4.6 (or 1.5.0)

### ISSUE THREAD

**Issue by saki7** [olbrich/ruby-units#116]
Since a year has passed since the last RubyGems release (`1.4.5`), I think it's time to publish a new release `1.4.6` or  `1.5.0` (the latter may be preferred if included commits break backward compatibility).

> Please note that ruby-units gem `1.4.5`does exists in RubyGems.org, however it's not tagged in this git repository (in this repository, the latest tag is `1.4.4`).

Before publishing `1.4.6` (otherwise `1.5.0`; depending on your choise), I think:
- ~~#112 must be closed, since the corresponding PR #115 has been merged (thanks!)~~
- #107 must be fixed, but need verification before merging.
- #108 must be merged, however, IMO, it must be included in next **major** release instead of **minor** release.  You need further investigation on the included commits, too.
- #104 must be re-considered carefully. IMO, this PR has a great chance of producing a regression.
- #111 can be easily fixed since it seems to have no regression.
- ~~#100 can be closed since the corresponding PR #99 has already been merged to master.~~
- ~~#102 must be rejected since ruby-units must handle expressions by rational. In principle, decimal results are **incorrect** in this library.~~

**Comment by olbrich** [comment]
Agreed, I need to spend some time on this soon.
