### ISSUE TITLE
No Fluid Ounce to Milliliter Conversion

### ISSUE THREAD

**Issue by sshaw** [olbrich/ruby-units#118]
```
irb [2.1.3] (ruby-units)$ Unit("8 fl oz") >> "ml"
ArgumentError: Incompatible Units ('8 fl*oz' not compatible with 'ml')
..
```

Any reason for this?

**Comment by olbrich** [comment]
Try...

   Unit("8 floz") >> "ml"

You will get something like... 

    473176473/2000000 ml  (or 236 ml).

**Comment by sshaw** [comment]
The problem with this is that no one (that I've seen) uses the abbreviation `floz` for fluid ounces. That abbreviation is [not listed here](https://en.wikipedia.org/wiki/Fluid_ounce) either. 

I can submit a patch for this that encompasses the issues raised in #117.

**Comment by sshaw** [comment]
Although what's the difference between `fl*oz` and `floz`?

**Comment by olbrich** [comment]
So the semi official abbreviation for it would be 'fl oz'.  However, RubyUnits doesn't allow spaces inside the name of a unit.  

`fl*oz` would imply that you are multiplying two separate units together, when in fact you are just referencing one.

**Comment by sshaw** [comment]
>>  Try...
>>  Unit("8 floz") >> "ml"

> I'm trying to stay away from too much special case parsing in general.

I would say `"floz"` is the special case :smirk_cat: 

I'm new to this library but since opening this issue I've read a lot more of the docs and have gone through the code; the library is pretty robust. I think it only makes sense to handle `"fl oz"`.  

In the meantime I'll be :monkey: patching :smile:
