### ISSUE TITLE
Modifying core types should be optional

### ISSUE THREAD

**Issue by kmcphillips** [olbrich/ruby-units#124]
This is a solid library. I can't find any unit tool in ruby that touches this one.

Unfortunately we can't bring it into our project because this gem opens up and modifies a number of core types: `Array`, `Date`, `Fixnum`, `Math`, `Numeric`, `Object`, `String`, `Time`

This is bad style and is dangerous. Is there a reason these core type modifications were made mandatory? They should be opt-in similar to how namespacing is done. These core extensions are depended on for internal implementation as well so I can't even selectively include units and conversions without modifying all those above classes.

**Comment by olbrich** [comment]
Some of these core modification are necessary and several are not.  I plan to make this a lot more configurable, but have not yet had a chance to implement the required changes.  Stay tuned.

**Comment by kreintjes** [comment]
Fixed with https://github.com/olbrich/ruby-units/pull/157
