### ISSUE TITLE
Deprecation Warning - Rails 4.1.0 - Ruby 2.0.0

### ISSUE THREAD

**Issue by josegrad** [olbrich/ruby-units#127]
Hi,

Thanks for the gem.
Got this using Rails 4.1.0 and Ruby 2.0.0

Works fine so far.

====================
Deprecation Warning
====================

Several convenience methods that ruby-units added to the string class have
been deprecated in this release.  These methods include String#to, String#from, String#ago, String#before and others.
If your code relies on these functions, they can be added back by adding this line to your code.

require 'ruby-units/string/extras'
# note that these methods do not play well with Rails, which is one of the reasons they are being removed.

The extra functions mostly work the same, but will no longer properly handle cases when they are called with strings..

'min'.from("4-1-2011") # => Exception

Pass in a Date, Time, or DateTime object to get the expected result.

They will go away completely in the next release, so it would be a good idea to refactor your code
to avoid using them.  They will also throw deprecation warnings when they are used.

**Comment by olbrich** [comment]
This is a deprecation warning from the gem warning about methods that are being removed.  If you aren't using them, there is nothing you need to do.
