### ISSUE TITLE
Conversion issue...?

### ISSUE THREAD

**Issue by krio** [olbrich/ruby-units#131]
I'm using Ruby 2.2.2 and a new gem install of ruby-units 1.4.5. Is this expected?

2.2.2 :003 > require 'ruby-units'
 => true 
2.2.2 :004 > unit = Unit("220 lbs")
 => 220 lbs 
2.2.2 :005 > unit.to_s
 => "220 lbs" 
2.2.2 :006 > unit.to_s('kg')
 => "498951607/5000000 kg" 
2.2.2 :007 > unit.to_s('kilograms')
 => "498951607/5000000 kg" 
2.2.2 :008 > unit.to_s('lbs')
 => "220 lbs"

**Comment by olbrich** [comment]
yes, it's expected.  Internally I use Rational numbers to avoid issues with round-off errors.  You can pass a format string to to_s if you want to have it represented as a float.  

    unit.to_s('%0.2f kg') #=> "99.79 kg"
