### ISSUE TITLE
The gem changes Ruby's default behavior (2.3.0)

### ISSUE THREAD

**Issue by anhkind** [olbrich/ruby-units#139]
I have the latest gem installed and got a weird bug today. This is what I got when running in `irb`

```
2.3.0 :001 > 29/24
 => 1
2.3.0 :002 > require 'ruby-units'
 => true
2.3.0 :003 > 29/24
 => (29/24)
```

Why do we have this behavior? Is it a bug somewhere?

**Comment by anhkind** [comment]
I think the bug is here https://github.com/olbrich/ruby-units/blob/master/lib/ruby_units/math.rb#L1.

**Comment by olbrich** [comment]
It's because we include 'mathn'.

**Comment by anhkind** [comment]
@olbrich Sorry, did you mean that by including the gem in the codebase, the users should expect unexpected behavior? It's __dangerous__ because people may not know what happens and will spend __A LOT OF__ time to figure it out, with cost of course. Changing default behavior of something you don't own is not recommended, I believe. I have no offense at all, just want to give feedback to make things better. I'm looking forward to your response. Thanks.

**Comment by anhkind** [comment]
I see, we have the same closed issue here https://github.com/olbrich/ruby-units/issues/134. For my case, the gem https://github.com/masa16/phys-units is working far better without unexpected behavior.
