### ISSUE TITLE
Please helpe

### ISSUE THREAD

**Issue by MDRecipes** [olbrich/ruby-units#143]
Hello
How do we use the gem 'ruby-units' in a relationship has_many through?
I have a recipe model
model ingredient
And a recipe_ingredient model, with "recipe_id, ingredient_id, quantity: decimal, measure: string"

I want to convert the quantities into a basic measurement
But I can not
I find a trick on github but it does not use the gem cocoon https://github.com/fenjiot/mixologist.git﻿
Can you make a tutorial for dummies?

**Comment by olbrich** [comment]
you could simply store 'unit.scalar' in the quantity field and 'unit.units' in measure field.  Note that this might not be adequate if you want to be able to sort on those fields in the database and they are not all converted to a consistent unit.
