### ISSUE TITLE
Parentheses in unit definition

### ISSUE THREAD

**Issue by humphreyja** [olbrich/ruby-units#151]
I have an instance where I have two "units" that have two different definitions.  A Unit could be either 130k seeds or 140k seeds.  I tried to define the units with the following:

```ruby
Unit.define("unit (140k)") do |unit|
  unit.definition = Unit("140000 seeds")
  unit.aliases = ["units (140k)", "per unit (140k)"]
  unit.display_name = "units (140k)"
end

Unit.define("unit (130k)") do |unit|
  unit.definition = Unit("130000 seeds")
  unit.aliases = ["units (130k)", "per unit (130k)"]
  unit.display_name = "units (130k)"
end
```

It keeps giving me a `ArgumentError: 'unit (130k)' Unit not recognized` when I try to use it.  It seems to me that parentheses are not allowed in the name.  How difficult would it be to get something like this to work?

**Comment by humphreyja** [comment]
Also, in attempting to find a better method I ran into this weird issue.  Why does the `unit` declarations work but not the `bag` declaration?

```ruby
Unit.define("bag") do |bag|
  bag.definition = Unit("80000 seeds")
  bag.aliases = ["bags", "bags - 80k", "per bag", "per bag - 80k"]
  bag.display_name = "bags - 80k"
end

Unit.redefine!("unit") do |unit|
  unit.definition = Unit("140000 seeds")
  unit.aliases = ["units", "units - 140k", "per unit", "per unit - 140k"]
  unit.display_name = "units - 140k"
end

Unit.define("unit - 130k") do |unit|
  unit.definition = Unit("130000 seeds")
  unit.aliases = ["units - 130k", "per unit - 130k"]
  unit.display_name = "units - 130k"
end

#==== Console ====

(irb)> Unit.new("per unit - 130k")
=> 1 units - 130k

(irb)> Unit.new("per bag - 80k")
ArgumentError: 'per bag - 80k' Unit not recognized
```

**Comment by olbrich** [comment]
It seems that the unit parsing is getting tripped up on the word boundaries in your definition.  If you do something like `unit_140k` it should work.  In the last case you show the `-` is also going to be problematic.

Currently ruby-units makes extensive use of carefully crafted regular expressions to parse the units.  There isn't much I can do to make this work the way you want it to without breaking other cases.
