### ISSUE TITLE
Unit conversion from inches to meters is not accurate

### ISSUE THREAD

**Issue by sandeepnagra** [olbrich/ruby-units#152]
say length = "16.00 in"

then if I do **length.to_unit** it becomes 16 in and the if I do **length.to('m')** it returns **254/625 m** instead of 0.4064 m

However the same works for values like length = "39.80 in" where length.to_unit.to('m') returns 1.01 m

**Comment by olbrich** [comment]
`(254/625).to_f  #=> 0.4064`
The library tries to keep things as rational numbers when appropriate for accuracy.
