### ISSUE TITLE
ruby-units changes behavior of Fixnum calculations

### ISSUE THREAD

**Issue by MartinKoerner** [olbrich/ruby-units#153]
IRB session without ruby-unit in Gemfile:
```ruby
irb(main):001:0>  4/3 # => 1
irb(main):002:0>  (4/3).class # => Fixnum
```

IRB session with ruby-unit in Gemfile:
```ruby
irb(main):001:0>  4/3 # => (4/3)
irb(main):002:0>  (4/3).class # => Rational
```

Of course, I can just call `(4/3).to_i` to get the old result, but I think, introducing the gem to an existing project should not require changes to unrelated code.

**Comment by olbrich** [comment]
https://github.com/olbrich/ruby-units#mathn

**Comment by MartinKoerner** [comment]
Doh! I didn't read to the end. Sorry for bothering you...

**Comment by olbrich** [comment]
@MartinKoerner No problem!
