### ISSUE TITLE
Monkey patching for more semantic usage

### ISSUE THREAD

**Issue by athityakumar** [olbrich/ruby-units#165]
I was wondering whether it'd be more readable if we monkey patch the numerical classes to have usage like the below.

```ruby
c = (3*10e8).m.s_-2
#=> 3000000000.0

c.class
#=> Float

c.units
#=> [Units('1 m'), Units(' s^-2')]
```

The "dynamic" powers (like `s_-2`) can be done easily using metaprogramming, by checking for regexp (`/s_/`) in the `method_missing` method and call the appropriate method if valid, else `super`. WDYT?

Edit: An even more simpler use case would be

```ruby
c = (3*10e8).m.s(-2)
```

**Comment by olbrich** [comment]
I would not recommend this for many reasons.. monkey patching fundamental classes like numbers is dangerous, namespace collisions are likely, and method missing is not great for performance.
