### ISSUE TITLE
BigDecimal Addition Slowness

### ISSUE THREAD

**Issue by joshkinabrew** [olbrich/ruby-units#166]
Hi there,

I'm experiencing some pretty interesting behavior when summing units together. I'm on Ruby 2.5.0 and Rails 5.1.5 but this can be reproduced in just an IRB console in Ruby 2.5.0

```ruby
require "ruby-units"
require 'bigdecimal'
require 'bigdecimal/util'

a = [
    [2.025, "gal"],
    [5.575, "gal"],
    [8.975, "gal"],
    [1.5, "gal"],
    [9, "gal"],
    [1.85, "gal"],
    [2.25, "gal"],
    [1.05, "gal"],
    [4.725, "gal"],
    [3.55, "gal"],
    [4.725, "gal"],
    [3.75, "gal"],
    [6.275, "gal"],
    [0.525, "gal"],
    [3.475, "gal"],
    [0.85, "gal"]
].map{|ns,nu| Unit.new(ns.to_d, nu)}

a.sum
```

This runs really slow. Like really slow.

Instead of just doing the last line`a.sum` let's do `a[0..10].sum`. It runs pretty quickly.

Now do this. (same scalar and unit values as before with no `.to_d` coercion.)

```ruby
b = [
    [2.025, "gal"],
    [5.575, "gal"],
    [8.975, "gal"],
    [1.5, "gal"],
    [9, "gal"],
    [1.85, "gal"],
    [2.25, "gal"],
    [1.05, "gal"],
    [4.725, "gal"],
    [3.55, "gal"],
    [4.725, "gal"],
    [3.75, "gal"],
    [6.275, "gal"],
    [0.525, "gal"],
    [3.475, "gal"],
    [0.85, "gal"]
].map{|ns,nu| Unit.new(ns, nu)}

b.sum
```
It runs very quickly. The numbers are floats, not BigDecimal.

What I've found is that summing arrays of units where the scalar value is a BigDecimal and the `.count` is greater than let's say 12 it performs abysmally. However summing arrays of units with a `.count` of less than 10 it works just fine.

The reason I'm dealing with BigDecimal is because that's what I get back from Rails on a decimal column.

Let me know if you need more detail.

**Comment by olbrich** [comment]
Which version of ruby-units are you using?  I'll assume it's 2.2.1

**Comment by olbrich** [comment]
@joshkinabrew please check out the branch `issue-166-bigdecimal-slowness` and see if that works for you.  In my testing with your benchmark script it made a huge difference.

**Comment by joshkinabrew** [comment]
@olbrich yes, v2.2.1 is what I'm running.

I've tested out that branch and it works great for me. Thanks for looking in to it so quickly!

**Comment by olbrich** [comment]
I'll go ahead and release a new version shortly.
