### ISSUE TITLE
Cannot Convert Concentration

### ISSUE THREAD

**Issue by AshtonKem** [olbrich/ruby-units#171]
I'm trying to use ruby-units to convert blood glucose units, but I'm getting an error about incompatible units. I'm under the impression that you can convert between mg/dL and mmol/L, but I'm getting the following error:

```
2.4.1 :009 > Unit.new("96 mg/dL").convert_to("mmol/l")
ArgumentError: Incompatible Units ('96 mg/dl' not compatible with 'mmol/l')
	from (irb):9
```

**Comment by olbrich** [comment]
You also need to use the molecular weight of glucose...

```
(Unit.new('96 mg/dl') / Unit.new('180.156 g/mol')).convert_to('mmol/l').to_s('%0.2f') #=> 5.33 mmol/l
```
