### ISSUE TITLE
Using mathn breaks atan2

### ISSUE THREAD

**Issue by dougo** [olbrich/ruby-units#173]
Even though ruby-units no longer requires mathn, our app currently relies on mathn behavior, so I wanted to require it explicitly until we finish removing our dependency on it. But that causes an error from ruby-units:
```
Loading development environment (Rails 5.2.1)
[1] pry(main)> Math.atan2(1,1)
=> 0.7853981633974483
[2] pry(main)> require 'mathn'
=> true
[3] pry(main)> Math.atan2(1,1)
NoMethodError: undefined method `unit_atan2' for CMath:Module
from /Users/dougo/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/ruby-units-2.3.0/lib/ruby_units/math.rb:118:in `atan2'
```
I haven't tried upgrading to Ruby 2.5 yet, but would it be feasible to fix this for 2.4.4 in the meantime?

**Comment by olbrich** [comment]
Fixing this is going to be somewhat tricky, but it seems that if you require 'mathn' before you require 'ruby-units' then this problem might go away.
