### ISSUE TITLE
Add a quantity/count unit of measure

### ISSUE THREAD

**Issue by taylorthurlow** [olbrich/ruby-units#182]
I'm not sure if this is in the scope of the gem, but I would find it useful if I were able to define a new unit which represents a numeric quantity - essentially just a ruby-units wrapper around a numeric value. Being able to define a unit called 'count' and treat it like any other `Unit` would simplify business logic significantly.

Let me know if this seems like a reasonable request, or if it's even possible to define a unit that has no definition based on another unit.

**Comment by olbrich** [comment]
This already works...

    Unit.new('1 each') + Unit.new('1 count') 
    # => 2 each

There are subtleties here.  They are freely convertable between each other, which sometimes makes sense, but sometimes does not.

**Comment by taylorthurlow** [comment]
Ah, I swear I tried this. Thanks!
