### ISSUE TITLE
can't convert µm to mg/mL

### ISSUE THREAD

**Issue by Kuassari** [olbrich/ruby-units#193]
"2 µm".convert_to('mg/ml') I get this error:

*** ArgumentError Exception: Incompatible Units ('2 um' not compatible with 'mg/ml')

how can I solve it?

**Comment by olbrich** [comment]
"2 µm" is the equivalent of 2 micro meters.  It's not possible to convert that to 'mg/ml'.  I suspect you are trying to convert 'micro molar' to 'mg/ml'.

If that's true you are still going to have problems without knowing the molecular weight of the solute.
