### ISSUE TITLE
Help with unit definition

### ISSUE THREAD

**Issue by frank-west-iii** [olbrich/ruby-units#195]
I need to see if I can define the units for plato and specific gravity.

The calculations are:

SG = 1+ (plato / (258.6 – ( (plato/258.2) *227.1) ) )
plato = (-1 * 616.868) + (1111.14 * sg) – (630.272 * sg^2) + (135.997 * sg^3)

I saw this issue here, which had the right keywords, but didn't help: https://github.com/olbrich/ruby-units/issues/58

Thanks for any light you can shed on this for me and thanks for the library!

**Comment by olbrich** [comment]
Ruby units only handles units that are linear conversions.  You'll need to write your own conversion functions unfortunately.

**Comment by frank-west-iii** [comment]
Awesome. Thanks for the response. That's what I was thinking, but was hoping 😀
