### ISSUE TITLE
conversions returning fractions instead of units

### ISSUE THREAD

**Issue by nodefiend** [olbrich/ruby-units#197]
Greetings!

When converting units, I am getting an output as a fraction. in `[15]` i use a conversion from your docs, and instead of getting `98.6tempF` (which is what your docs say i should get)  I am getting a fraction.

__Ruby Console:__
```
[14] pry(main)> Unit.new("1 lb").convert_to("kg")
=> 45359237/100000000 kg
[15] pry(main)> Unit.new('37 tempC').convert_to('tempF')
=> 21682369299742711/219902325555200 tempF
[16] pry(main)> 

```

**Comment by olbrich** [comment]
`21682369299742711/219902325555200.to_f #=> 98.59999999999997`

Ruby units uses fractions internally whenever it can to preserve accuracy and minimize rounding errors inherent in floating point operations.
