### ISSUE TITLE
Resolution appears to be lost when coverting bytes to GiB

### ISSUE THREAD

**Issue by gee-forr** [olbrich/ruby-units#203]
Hi there,

Firstly - thank you so much for this stellar library - it's become a core part of our dependencies, and we love using it everyday.

I've noticed something weird when converting bytes to GiB... It appears that when I convert bytes to GiB I lose any decimal places.

It might be easier to show you with an example using `2.3.1`.

```ruby
Unit.new('1.5 GiB').convert_to('bytes').convert_to("GiB") # => 1.5 GiB

Unit.new('1610610000 bytes').convert_to('GiB') # => 1 GiB (but it should be 1.5 GiB)

Unit.new('1610610000 bytes').convert_to('GiB').convert_to('bytes') # => 1.07374e+09 B 

# (i.e. 1073740000.0 meaning, 536,870,000 bytes went missing somewhere in the conversion.)
```

Please let me know if there's anything I can do to assist.

**Comment by gee-forr** [comment]
Here is a failing spec which matches the other spec in the `spec/ruby_units/bugs_spec.rb` spec file.

```ruby
describe 'Github issue #203' do
  let(:bytes) { 1_610_610_000 }

  it 'should convert from bytes to GiB and back, and not lose any value' do
    expect(Unit.new("#{bytes} bytes").convert_to("GiB").convert_to("bytes").scalar).to eq bytes
  end
end
```
The current output I'm getting is: 

```
$ rspec spec/ruby_units/bugs_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 31515
.F

Failures:

  1) Github issue #203 should convert from bytes to GiB and back, and not lose any value
     Failure/Error: expect(Unit.new("#{bytes} bytes").convert_to("GiB").convert_to("bytes").scalar).to eq bytes

       expected: 1610610000
            got: 1073741824

       (compared using ==)
     # ./spec/ruby_units/bugs_spec.rb:16:in `block (2 levels) in <top (required)>'

Finished in 0.02785 seconds (files took 1.43 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/ruby_units/bugs_spec.rb:15 # Github issue #203 should convert from bytes to GiB and back, and not lose any value

Randomized with seed 31515

Coverage report generated for RSpec to /Users/gabrielf/Projects/personal/ruby-units/coverage. 1108 / 1444 LOC (76.73%) covered.
SimpleCov failed with exit 1
```

**Comment by olbrich** [comment]
@gee-forr Thanks for your report, I'm looking into it.

**Comment by olbrich** [comment]
I haven't fully tracked down the cause, but you are getting tripped up by integer math.

    1610610000 / 1073741824 #=> 1

A work around for this problem is to provide your scalar as a rational number.

    Unit.new(1610610000.to_r, 'bytes').convert_to('GiB') #=> 100663125/67108864 GiB

I admit this is a bit counter-intuitive so I'm thinking about how best to deal with this behavior.

**Comment by zenithlight** [comment]
It might be possible to always store the unmodified original value, then when converting to another unit, add it to a list of "scaling factors" stored alongside it. Then, when accessing the quantity, compute the original value multiplied through the scaling factors as a Rational. Then cast to the type of the original value. For long chains of conversions, you could probably cancel out some of the scaling factors as an optimization.

**Comment by gee-forr** [comment]
hi @olbrich - hope you're doing well during this difficult time...

I was wondering if you've made any headway into solving this? If not, is there something I could do - with your guidance - to put a patch in to fix it? We got bitten by this bug again today.

**Comment by foomip** [comment]
I think if the scalar value is always saved as a real or float number should solve it? Probably more work than I am thinking to change this in the back-end but that should get rid of any integer division issues.

**Comment by foomip** [comment]
This is basically the workaround we have been using 

`ruby
  Unit.new(1610610000.to_f, 'bytes').convert_to('GiB') => 1.5 GiB
`

**Comment by SparkusK** [comment]
Would it be a bad idea to monkey-patch the `/` operator to always use float values?

**Comment by gee-forr** [comment]
> Would it be a bad idea to monkey-patch the `/` operator to always use float values?

Haha - that would be a very bad idea :)

**Comment by SparkusK** [comment]
Why though? I mean, like, scoped to specifically `Unit` objects, when dealing with this specific stuff. If we're getting tripped up by Integer math, we should tell the `Unit` to not use Integer division but float division instead, and the way we go about that is to tell it to treat the `Int`s as `Float`s.

**Comment by gee-forr** [comment]
> Why though? I mean, like, scoped to specifically `Unit` objects, when dealing with this specific stuff. If we're getting tripped up by Integer math, we should tell the `Unit` to not use Integer division but float division instead, and the way we go about that is to tell it to treat the `Int`s as `Float`s.

You could [monkey patch it using refinements](https://docs.ruby-lang.org/en/2.4.0/syntax/refinements_rdoc.html) so it's only available within the Unit class, but that is like killing a spider with a tank.

The cleaner solution would be to store the internal value as a float so that it converts in a non-surprising manner.

**Comment by SparkusK** [comment]
I dunno man, I don't think storing the amount of `bytes` as a `float` is cleaner. There might be some merits in terms of performance - if we _do_ end up storing it as a float, then the conversion is only done once (on object construction), instead of every time we want to do a division; though, there are probably some caching/memoizing tricks to get around that. Also, I realise you're specifying it as an _internal_ representation, so we could make it so it still only accepts `int` values from the outside.

Regardless of that, I can't shake the feel that storing it as a `float` is some kind of code smell. It feels like a hack. Monkey patching the div operator using a refinement seems like the optimal solution, because we're making it explicit and clear that we want to avoid Ruby's default of integer division for this particular case, as opposed to relying on someone knowing about implicit, buried information.

But maybe that's just me :laughing:

**Comment by gee-forr** [comment]
fantastic news on a permanent in-gem solution to this @olbrich - it's much appreciated. We're eagerly looking forward to the rubygems release :)

Thank you so much!
