### ISSUE TITLE
round function should return decimal number (sometimes returnes fraction)

### ISSUE THREAD

**Issue by PsychoPhobic** [olbrich/ruby-units#231]
on unit multiply with round function should return decimal number but sometimes returns fraction
i have this problem with following code:
(unit1 * unit2).convert_to('m/min').round(1)
the shown result in view is most time a decimal number. But sometimes it is a fraction number like

219/10 m/min instead of 21.9 m/min

i can reproduce it with:
unit1 = Unit.new('2187 min^-1')
unit2 = Unit.new('10 mm')
(unit1 * unit2).convert_to('m/min').round(1)

ruby 3.0.0p0
rails 6.1.3.1

**Comment by olbrich** [comment]
Unit conversion can result in `Rational` scalar values (which is done to preserve precision). Rounding a Rational scalar follows the rules of rounding for Rational numbers. If you are trying to format units for output, I recommend using `to_s('%0.1f')` which will represent the scalar as a single digit float regardless of what the type of the scalar actually is.

I did notice that I had been passing arguments incorrectly for `round`, `truncate`, `ceil` and `floor` as those signatures changed around Ruby 2.5.  The code now just forwards whatever arguments are provided to the method.
