### ISSUE TITLE
Awareness of Units Summit Summer 2022

### ISSUE THREAD

**Issue by stuchalk** [olbrich/ruby-units#267]
Sorry this is not an issue but a message just trying to get in touch with the developers of this project. There will be three coordinated session at ScIDataCon 2022. See this page for more info. https://codata.org/initiatives/task-groups/drum/units-summit-recap-meeting/

Stuart Chalk
DRUM Secretary
https://codata.org/initiatives/task-groups/drum/

**Comment by olbrich** [comment]
Thanks, Stuart!
