### ISSUE TITLE
Parenthesis in unit names aren't recognised

### ISSUE THREAD

**Issue by penguoir** [olbrich/ruby-units#286]
If we define a unit that includes parenthesis:

```ruby
Unit.define "m (meters)" do |unit|
  unit.definition = "1 m".to_unit
end
```
Then it won't be recognised:

```ruby
"1 m (meters)".to_unit
```
(This raises `'1 m (meters)' Unit not recognized (ArgumentError)`)

**Comment by olbrich** [comment]
This use case is not currently supported and probably won't work well in a general use case.  PRs are welcome to explore this, closing for now.
