### ISSUE TITLE
ArgumentError parsing 1:00

### ISSUE THREAD

**Issue by mdi** [olbrich/ruby-units#321]
According to the docs, `Unit.new("1:00")` should return `1 h`, but instead it actually returns:

```
irb(main):001> Unit.new("1:00")
/usr/local/bundle/gems/ruby-units-3.0.0/lib/ruby_units/unit.rb:1652:in `parse': '1:00' Unit not recognized (ArgumentError)

      raise(ArgumentError, "'#{passed_unit_string}' Unit not recognized") unless used.empty?
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mdi** [comment]
Hi @olbrich, is there a plan to merge #323 and release this soon?

**Comment by olbrich** [comment]
@mdi Can you verify that this works for you?  If so, I'll make a point of releasing it this week.

**Comment by mdi** [comment]
@olbrich yes, it fixes the issue.
