### ISSUE TITLE
Unit format if numerator is 1 in unit faction

### ISSUE THREAD

**Issue by PsychoPhobic** [olbrich/ruby-units#335]
Unit.new("1000 min^-1") is shown as 1000 1/min but it looks like 10001/min in mathml

units with numerator = 1 in unit fraction should use notation like 1000 min^-1 with <msup> tag

**Comment by olbrich** [comment]
This library makes no attempt to support MathML, but you can probably build some custom support be inspecting the `numerator` and `denominator` of a particular instance of a unit.

**Comment by PsychoPhobic** [comment]
What i mean is Unit.new("1000 min^-1").to_s #=> retrurns "1000 1/min"
maybe it should return "1000 min^-1" in gerneral for readability if only units exists with power of -1. This would be also allow to directly use it inline in Katex string.

is there at the moment any methods for getting nummerator and denominator for only the Unit part ("1/min")?

**Comment by olbrich** [comment]
@PsychoPhobic take a look at the associated PR and let me know if that meets your needs.
