### ISSUE TITLE
round/ceil/floor for centi prefix not working

### ISSUE THREAD

**Issue by eakischuk** [olbrich/ruby-units#343]
I am trying to round an area with the unit `cm^2`, which is leading to an error:

```ruby
unit = Unit.new(22.5, "cm^2")
=> 22.5 cm^2
unit.ceil
=> '22.5 <centi><meter><centi><meter>/<1>' Unit not recognized (ArgumentError)
```

Other complex units with prefix (such as mm^2) round just fine, as does a simple centi prefixed unit (such as cm). 

This is similar to the previously reported/solved bug from [PR #92](https://github.com/olbrich/ruby-units/pull/92), but the `unit_regex` does not include "|c|" and therefore does not recognize the `centi` prefix. 

We were able to test this by refactoring the `while` loop from [these lines](https://github.com/olbrich/ruby-units/blob/89fb3a81ef56be823c3ec5d30de560689953ff42/lib/ruby_units/unit.rb#L1643-L1647) as follows:
```
while unit_string.gsub!(/(<#{"c|" + self.class.unit_regex})><(#{"c|" + self.class.unit_regex}>)/, '\1*\2')
  # collapse <x><y><z> into <x*y*z>...
end
```

It occurs to me that `unit_regex` may not be the intended place to hold prefixes and other prefixes are included incidentally via aliases for other units.

**Comment by carl-printreleaf** [comment]
👍

**Comment by olbrich** [comment]
Thanks for reporting this, I'll look into it shortly.

**Comment by olbrich** [comment]
@eakischuk Please try the branch associated with this issue and ensure that it works for you.

**Comment by eakischuk** [comment]
@olbrich this works, thank you so much!
